source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'YipYipSwiftExample' do
    pod 'YipYipSwift', :path => '../'
end
    
target 'YipYipSwift_Tests' do
    pod 'YipYipSwift', :path => '../'
end
